# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 7) do

  create_table "api_usages", :force => true do |t|
    t.column "api_id",  :string,   :limit => 32, :null => false
    t.column "room_id", :string,   :limit => 32
    t.column "ticket",  :string,   :limit => 20
    t.column "used_at", :datetime
  end

  create_table "messages", :force => true do |t|
    t.column "type",         :string,   :limit => 32
    t.column "occupant_id",  :integer
    t.column "user_id",      :integer
    t.column "nickname",     :string,   :limit => 32
    t.column "new_nickname", :string,   :limit => 32
    t.column "source",       :string,   :limit => 13
    t.column "client_type",  :string,   :limit => 9
    t.column "icon_url",     :string
    t.column "timestamp",    :datetime
    t.column "room_id",      :string,   :limit => 32
    t.column "score",        :float
    t.column "text",         :string
  end

  create_table "rooms", :force => true do |t|
    t.column "room_id",             :string,  :limit => 32
    t.column "name",                :string
    t.column "description",         :string
    t.column "url",                 :string
    t.column "icon_url",            :string
    t.column "counter",             :integer
    t.column "max_user_message_id", :integer
    t.column "requires_password",   :boolean
    t.column "chatter_count",       :integer
    t.column "observer_count",      :integer
    t.column "timezone",            :string,  :limit => 32
  end

  create_table "rooms_tags", :id => false, :force => true do |t|
    t.column "room_cid", :integer
    t.column "tag_cid",  :integer
  end

  create_table "rooms_users", :id => false, :force => true do |t|
    t.column "room_cid",   :integer
    t.column "user_cid",   :integer
    t.column "room_group", :string,  :limit => 16
  end

  create_table "tags", :force => true do |t|
    t.column "name",         :string, :limit => 80
    t.column "display_name", :string, :limit => 80
    t.column "url",          :string, :limit => 100
  end

  create_table "users", :force => true do |t|
    t.column "user_id",          :integer
    t.column "email",            :string,   :limit => 64
    t.column "default_nickname", :string,   :limit => 32
    t.column "icon_url",         :string,   :limit => 128
    t.column "counter",          :integer
    t.column "description",      :string
    t.column "valid",            :boolean
    t.column "carrier",          :string,   :limit => 1
    t.column "uid",              :string,   :limit => 40
    t.column "password",         :string,   :limit => 40
    t.column "last_login",       :datetime
    t.column "easy_login",       :boolean,                 :default => false
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
  end

end
